-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

REVOKE ALL PRIVILEGES ON SCHEMA public FROM ims_user;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM ims_user;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM ims_user;
DROP USER ims_user;

CREATE USER ims_user WITH LOGIN PASSWORD 'password123'; 
GRANT ALL PRIVILEGES ON SCHEMA public TO ims_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ims_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ims_user;


CREATE TABLE IF NOT EXISTS sale_transaction
(
    transaction_id integer,
    date date,
    cashier_id integer,
    subtotal numeric(10, 2),
    tax numeric(10, 2),
    discount numeric(10, 2),
    total numeric(10, 2)
);

CREATE TABLE IF NOT EXISTS saleitem
(
    saleitem_id integer,
    transaction_id integer,
    product_id integer,
    "quantity " integer,
    price_at_sale numeric(10, 2)
);

CREATE TABLE IF NOT EXISTS              products (
    id SERIAL PRIMARY KEY,

    product_code VARCHAR(50),

    name VARCHAR(255) NOT NULL,
    category_id INTEGER,

    price NUMERIC(10,2) NOT NULL DEFAULT 0,
    current_quantity INTEGER NOT NULL DEFAULT 0,

    reorder_threshold INTEGER DEFAULT 0,

    archived BOOLEAN NOT NULL DEFAULT FALSE,

    created_by INTEGER,
    last_updated_by INTEGER,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- Fast search for active products by name
CREATE INDEX IF NOT EXISTS idx_products_name
ON products (name);


CREATE INDEX IF NOT EXISTS idx_products_archived
ON products (archived);

-- Test Data
INSERT INTO products (product_code, name, category_id, price, current_quantity, reorder_threshold, archived, created_by, last_updated_by)
VALUES ('MILK001', 'Whole Milk 1L', 1, 2.49, 120, 20, FALSE, 1, 1);

INSERT INTO products (product_code, name, category_id, price, current_quantity, reorder_threshold, archived, created_by, last_updated_by)
VALUES ('BRED002', 'Whole Wheat Bread', 2, 1.99, 80, 15, FALSE, 1, 1);

INSERT INTO products (product_code, name, category_id, price, current_quantity, reorder_threshold, archived, created_by, last_updated_by)
VALUES ('APPL003', 'Red Apples (1kg)', 3, 3.50, 60, 10, FALSE, 1, 1);

INSERT INTO products (product_code, name, category_id, price, current_quantity, reorder_threshold, archived, created_by, last_updated_by)
VALUES ('EGGS004', 'Large Eggs (12 pack)', 4, 4.25, 40, 8, FALSE, 1, 1);

INSERT INTO products (product_code, name, category_id, price, current_quantity, reorder_threshold, archived, created_by, last_updated_by)
VALUES ('RICE005', 'Basmati Rice 5kg', 5, 12.99, 25, 5, FALSE, 1, 1);


END;